// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DataFrameExample
List DataFrameExample(const DataFrame& DF);
RcppExport SEXP RcppExamples_DataFrameExample(SEXP DFSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const DataFrame& >::type DF(DFSEXP);
    __result = Rcpp::wrap(DataFrameExample(DF));
    return __result;
END_RCPP
}
// DateExample
List DateExample(DateVector& dv, DatetimeVector& dtv);
RcppExport SEXP RcppExamples_DateExample(SEXP dvSEXP, SEXP dtvSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DateVector& >::type dv(dvSEXP);
    Rcpp::traits::input_parameter< DatetimeVector& >::type dtv(dtvSEXP);
    __result = Rcpp::wrap(DateExample(dv, dtv));
    return __result;
END_RCPP
}
// ListExamples
List ListExamples(const List& rparam);
RcppExport SEXP RcppExamples_ListExamples(SEXP rparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const List& >::type rparam(rparamSEXP);
    __result = Rcpp::wrap(ListExamples(rparam));
    return __result;
END_RCPP
}
// MatrixExample
List MatrixExample(const NumericMatrix& orig);
RcppExport SEXP RcppExamples_MatrixExample(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type orig(origSEXP);
    __result = Rcpp::wrap(MatrixExample(orig));
    return __result;
END_RCPP
}
// NumericVectorExample
List NumericVectorExample(const NumericVector& orig);
RcppExport SEXP RcppExamples_NumericVectorExample(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type orig(origSEXP);
    __result = Rcpp::wrap(NumericVectorExample(orig));
    return __result;
END_RCPP
}
// RcppRNGs
DataFrame RcppRNGs(const int n);
RcppExport SEXP RcppExamples_RcppRNGs(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    __result = Rcpp::wrap(RcppRNGs(n));
    return __result;
END_RCPP
}
// StringVectorExample
List StringVectorExample(const StringVector& orig);
RcppExport SEXP RcppExamples_StringVectorExample(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const StringVector& >::type orig(origSEXP);
    __result = Rcpp::wrap(StringVectorExample(orig));
    return __result;
END_RCPP
}
