// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DataFrameExample
List DataFrameExample(DataFrame DF);
RcppExport SEXP RcppExamples_DataFrameExample(SEXP DFSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type DF(DFSEXP );
        List __result = DataFrameExample(DF);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// DateExample
List DateExample(DateVector dv, DatetimeVector dtv);
RcppExport SEXP RcppExamples_DateExample(SEXP dvSEXP, SEXP dtvSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DateVector >::type dv(dvSEXP );
        Rcpp::traits::input_parameter< DatetimeVector >::type dtv(dtvSEXP );
        List __result = DateExample(dv, dtv);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// ListExamples
List ListExamples(List rparam);
RcppExport SEXP RcppExamples_ListExamples(SEXP rparamSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type rparam(rparamSEXP );
        List __result = ListExamples(rparam);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// newRcppMatrixExample
List newRcppMatrixExample(NumericMatrix orig);
RcppExport SEXP RcppExamples_newRcppMatrixExample(SEXP origSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type orig(origSEXP );
        List __result = newRcppMatrixExample(orig);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// NumericVectorExample
List NumericVectorExample(NumericVector orig);
RcppExport SEXP RcppExamples_NumericVectorExample(SEXP origSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type orig(origSEXP );
        List __result = NumericVectorExample(orig);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// RcppRNGs
DataFrame RcppRNGs(int n);
RcppExport SEXP RcppExamples_RcppRNGs(SEXP nSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        DataFrame __result = RcppRNGs(n);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
