# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DataFrameExample <- function(DF) {
    .Call('RcppExamples_DataFrameExample', PACKAGE = 'RcppExamples', DF)
}

DateExample <- function(dv, dtv) {
    .Call('RcppExamples_DateExample', PACKAGE = 'RcppExamples', dv, dtv)
}

ListExamples <- function(rparam) {
    .Call('RcppExamples_ListExamples', PACKAGE = 'RcppExamples', rparam)
}

newRcppMatrixExample <- function(orig) {
    .Call('RcppExamples_newRcppMatrixExample', PACKAGE = 'RcppExamples', orig)
}

NumericVectorExample <- function(orig) {
    .Call('RcppExamples_NumericVectorExample', PACKAGE = 'RcppExamples', orig)
}

RcppRNGs <- function(n) {
    .Call('RcppExamples_RcppRNGs', PACKAGE = 'RcppExamples', n)
}

